- name: "Create directory: {{ home_directory }}"
  ansible.builtin.file:
    state: "directory"
    path: "{{ home_directory }}"

- name: "Create group: {{ local_group }}"
  group:
    name: "{{ local_group }}"
    gid: "{{ local_group_gid }}"

- name: "Create user: {{ local_account }}"
  user:
    name: "{{ local_account }}"
    comment: "{{ application_name }} service account"
    uid: "{{ local_account_uid }}"
    group: "{{ local_group }}"
    home: "{{ home_directory }}"
    create_home: no
    expires: -1

- name: "Change ownership for directory: {{ home_directory }}"
  ansible.builtin.file:
    path: "{{ home_directory }}"
    state: "directory"
    recurse: yes
    group: "{{ local_group }}"
    owner: "{{ local_account }}"

- name: "Copy sudoers file for user: {{ local_account }}"
  template:
    src: "sudoers_{{ application_name }}.j2"
    dest: "/etc/sudoers.d/sudoers_{{ application_name }}"
    validate: "visudo --check --file=%s"
    group: "root"
    owner: "root"
    # mode: 0440
    mode: "u=r,g=r,o="
